apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-app
          image: souljay/newhello-world:v1
          ports:
            - containerPort: 4000
---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello-world-service
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30001

